# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollect',
            name='date',
            field=models.CharField(default='23', max_length=20),
        ),
    ]
