# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200314_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('advice', models.TextField()),
            ],
        ),
    ]
