# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=2019902913914920942),
            preserve_default=False,
        ),
    ]
