# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-24 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_data_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='advice',
        ),
    ]
