# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_delete_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_c',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
