# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200425_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_c',
            name='time',
            field=models.DateField(),
        ),
    ]
